export const fieldsMap = {
  currency: [
    {
      field: "CompanyName",
      headerText: "Company",
      width: "140",
      visible: true,
    },
    { field: "Name", headerText: "Name", width: "150", visible: true },
    {
      field: "MailingName",
      headerText: "Formal Name",
      width: "140",
      visible: true,
    },
    {
      field: "OriginalName",
      headerText: "Original Name",
      width: "140",
      visible: true,
    },
    {
      field: "ExpandedSymbol",
      headerText: "Symbol",
      width: "130",
      visible: true,
    },
    {
      field: "DecimalSymbol",
      headerText: "Decimal Symbol",
      width: "140",
      visible: true,
    },
    {
      field: "DecimalPlaces",
      headerText: "Decimal Places",
      width: "140",
      visible: true,
    },
    {
      field: "DecimalPlacesForPrinting",
      headerText: "Decimal Place Print",
      width: "200",
      visible: true,
    },
    {
      field: "CreatedDate",
      headerText: "Uploaded On",
      width: "160",
      visible: true,
    },
    { field: "Status", headerText: "Status", width: "140", visible: true },
  ],
  company: [
    { field: "RemoteCmpName", headerText: "Name", width: "150", visible: true },
    {
      field: "RemoteCmpAddress",
      headerText: "Address",
      width: "250",
      visible: true,
    },
    {
      field: "RemoteCmpCountry",
      headerText: "Country",
      width: "150",
      visible: true,
    },
    {
      field: "RemoteCmpState",
      headerText: "State",
      width: "150",
      visible: true,
    },
    {
      field: "RemoteCmpPincode",
      headerText: "]Pincode",
      width: "150",
      visible: true,
    },
    {
      field: "RemoteCmpEmail",
      headerText: "Email",
      width: "190",
      visible: true,
    },
    {
      field: "RemoteCmpBaseCurrency",
      headerText: "Currency",
      width: "160",
      visible: true,
    },
    {
      field: "RemoteCmpBooksDate",
      headerText: "Book Start Date",
      width: "180",
      visible: true,
    },
    { field: "GSTNo", headerText: "GST No.", width: "180", visible: true },
    { field: "CINNo", headerText: "CIN No.", width: "180", visible: true },
    { field: "PANNo", headerText: "Pan No.", width: "180", visible: true },
    {
      field: "AdditionalField1",
      headerText: "Attribute 1",
      width: "160",
      visible: true,
    },
    {
      field: "AdditionalField2",
      headerText: "Attribute 2",
      width: "160",
      visible: true,
    },
    {
      field: "AdditionalField3",
      headerText: "Attribute 3",
      width: "160",
      visible: true,
    },
    {
      field: "AdditionalField4",
      headerText: "Attribute 4",
      width: "160",
      visible: true,
    },
    {
      field: "AdditionalField5",
      headerText: "Attribute 5",
      width: "160",
      visible: true,
    },
    {
      field: "CreatedDate",
      headerText: "Uploaded On",
      width: "160",
      visible: true,
    },
  ],
  costCategory: [
    {
      field: "CompanyName",
      headerText: "Company",
      width: "140",
      visible: true,
    },
    { field: "Name", headerText: "Name", width: "100", visible: true },
    {
      field: "CreatedDate",
      headerText: "Uploaded ON",
      width: "170",
      visible: true,
    },

    { field: "Status", headerText: "Status", width: "130", visible: true },
  ],
  costCenter: [
    {
      field: "CompanyName",
      headerText: "Company",
      width: "140",
      visible: true,
    },
    { field: "Name", headerText: "Name", width: "130", visible: true },

    {
      field: "ParentName",
      headerText: "Parent",
      width: "150",
      visible: true,
    },

    {
      field: "CreatedDate",
      headerText: "Uploaded On",
      width: "150",
      visible: true,
    },
    { field: "Status", headerText: "Status", width: "130", visible: true },
  ],
  group: [
    {
      field: "CompanyName",
      headerText: "Company",
      width: "140",
      visible: true,
    },
    { field: "Name", headerText: "Name", width: "130", visible: true },

    {
      field: "ReservedName",
      headerText: "Reserve Name",
      width: "140",
      visible: true,
    },

    {
      field: "ParentName",
      headerText: "Parent",
      width: "150",
      visible: true,
    },
    {
      field: "AccountType",
      headerText: "Account Type",
      width: "150",
      visible: true,
    },
    {
      field: "CreatedDate",
      headerText: "Uploaded ON",
      width: "170",
      visible: true,
    },
    ,
    { field: "IsActive", headerText: "Status", width: "130", visible: true },
  ],
  stockCategory: [
    {
      field: "CompanyName",
      headerText: "Company",
      width: "140",
      visible: true,
    },
    { field: "Name", headerText: "Name", width: "130", visible: true },

    {
      field: "ParentGUID",
      headerText: "Parent",
      width: "200",
      visible: true,
    },
    {
      field: "CreatedDate",
      headerText: "Uploaded ON",
      width: "170",
      visible: true,
    },
    { field: "Status", headerText: "Status", width: "130", visible: true },
  ],
  stockGodown: [
    {
      field: "CompanyName",
      headerText: "Company",
      width: "140",
      visible: true,
    },
    { field: "Name", headerText: "Name", width: "130", visible: true },

    {
      field: "ParentGUID",
      headerText: "Parent",
      width: "200",
      visible: true,
    },
    {
      field: "CreatedDate",
      headerText: "Uploaded ON",
      width: "170",
      visible: true,
    },
    { field: "Status", headerText: "Status", width: "130", visible: true },
  ],
  stockGroup: [
    {
      field: "CompanyName",
      headerText: "Company",
      width: "140",
      visible: true,
    },
    { field: "Name", headerText: "Name", width: "130", visible: true },

    {
      field: "ParentGUID",
      headerText: "Parent",
      width: "200",
      visible: true,
    },
    {
      field: "CreatedDate",
      headerText: "Uploaded ON",
      width: "170",
      visible: true,
    },
    { field: "Status", headerText: "Status", width: "130", visible: true },
  ],
  stockUnit: [
    {
      field: "CompanyName",
      headerText: "Company",
      width: "140",
      visible: true,
    },
    { field: "Name", headerText: "Name", width: "130", visible: true },

    {
      field: "DecimalPlaces",
      headerText: "Decimal Place",
      width: "150",
      visible: true,
    },
    {
      field: "OrignalName",
      headerText: "Original Name",
      width: "160",
      visible: true,
    },
    {
      field: "CreatedDate",
      headerText: "Uploaded On",
      width: "160",
      visible: true,
    },
    { field: "Status", headerText: "Status", width: "130", visible: true },
  ],
  StockItem: [
    {
      field: "CompanyName",
      headerText: "Company",
      width: "140",
      visible: true,
    },
    { field: "Name", headerText: "Name", width: "130", visible: true },

    {
      field: "ParentGUID",
      headerText: "Group",
      width: "200",
      visible: true,
    },

    {
      field: "CategoryGUID",
      headerText: "Category",
      width: "150",
      visible: true,
    },
    {
      field: "CategoryName",
      headerText: "Category Name",
      width: "150",
      visible: true,
    },
    {
      field: "Description",
      headerText: "Description",
      width: "150",
      visible: true,
    },
    { field: "Remarks", headerText: "Remark", width: "130", visible: true },
    {
      field: "CostingMethod",
      headerText: "Costing Method",
      width: "160",
      visible: true,
    },

    {
      field: "UomGUID",
      headerText: "UOM",
      width: "130",
      visible: true,
    },

    {
      field: "AltuomGUID",
      headerText: "Alt UOM",
      width: "180",
      visible: true,
    },

    {
      field: "Conversion",
      headerText: "Conversion",
      width: "150",
      visible: true,
    },
    {
      field: "Denominator",
      headerText: "Denominator",
      width: "150",
      visible: true,
    },
    {
      field: "OpeningBalance",
      headerText: "Opening Balance",
      width: "170",
      visible: true,
    },
    {
      field: "OpeningValue",
      headerText: "Opening Value",
      width: "170",
      visible: true,
    },
    {
      field: "OpeningRate",
      headerText: "Opening Rate",
      width: "150",
      visible: true,
    },
    {
      field: "CreatedDate",
      headerText: "Uploaded ON",
      width: "170",
      visible: true,
    },
    { field: "Status", headerText: "Status", width: "120", visible: true },
  ],
  voucherType: [
    {
      field: "CompanyName",
      headerText: "Company",
      width: "140",
      visible: true,
    },
    { field: "Name", headerText: "Name", width: "130", visible: true },

    {
      field: "ReservedName",
      headerText: "Reserved Name",
      width: "170",
      visible: true,
    },

    {
      field: "ParentGUID",
      headerText: "Parent ",
      width: "200",
      visible: true,
    },
    {
      field: "CreatedDate",
      headerText: "Uploaded ON",
      width: "170",
      visible: true,
    },
    { field: "Status", headerText: "Status", width: "120", visible: true },
  ],
  settingMaster: [
    {
      field: "SettingName",
      headerText: "Setting Name",
      width: "170",
      visible: true,
    },
    {
      field: "SettingValue",
      headerText: "Setting Value",
      width: "170",
      visible: true,
    },
    {
      field: "Description",
      headerText: "Description",
      width: "150",
      visible: true,
    },
    { field: "Status", headerText: "Status", width: "130", visible: true },
    {
      field: "CreatedByUserName",
      headerText: "Created By",
      width: "150",
      visible: true,
    },
    {
      field: "CreatedOn",
      headerText: "Created On",
      width: "150",
      visible: true,
    },
    {
      field: "UpdatedByUserName",
      headerText: "Updated By",
      width: "150",
      visible: true,
    },
    {
      field: "UpdatedOn",
      headerText: "Updated On",
      width: "50",
      visible: true,
    },
  ],
  designation: [
    {
      field: "DesignationCode",
      headerText: "Designation Code",
      width: "200",
      visible: true,
    },
    {
      field: "DesignationName",
      headerText: "Designation Name",
      width: "200",
      visible: true,
    },
    { field: "Status", headerText: "Status", width: "130", visible: true },
    {
      field: "CreatedByUserName",
      headerText: "Created By",
      width: "150",
      visible: true,
    },
    {
      field: "CreatedOn",
      headerText: "Created On",
      width: "150",
      visible: true,
    },
    {
      field: "ModifiedByUserName",
      headerText: "Updated By",
      width: "150",
      visible: true,
    },
    {
      field: "ModifiedOn",
      headerText: "Updated On",
      width: "150",
      visible: true,
    },
  ],
  departmentTable: [
    {
      field: "DepartmentCode",
      headerText: "Department Code",
      width: "180",
      visible: true,
    },
    {
      field: "DepartmentName",
      headerText: "Department Name ",
      width: "180",
      visible: true,
    },
    { field: "Status", headerText: "Status", width: "130", visible: true },
    {
      field: "CreatedByUserName",
      headerText: "Created By",
      width: "130",
      visible: true,
    },
    {
      field: "CreatedOn",
      headerText: "Created On",
      width: "130",
      visible: true,
    },
    {
      field: "ModifiedByUserName",
      headerText: "Updated By",
      width: "150",
      visible: true,
    },
    {
      field: "ModifiedOn",
      headerText: "Updated On",
      width: "130",
      visible: true,
    },
  ],
  employeeTable: [
    {
      field: "EmployeeCode",
      headerText: "Employee Code",
      width: "160",
      visible: true,
    },
    {
      field: "EmployeeName",
      headerText: "Employee Name",
      width: "160",
      visible: true,
    },
    { field: "Mobile", headerText: "Mobile", width: "130", visible: true },
    { field: "Email", headerText: "Email", width: "160", visible: true },
  ],
  role: [
    { field: "RoleName", headerText: "Role Name", width: "160", visible: true },
  ],
  User: [
    { field: "UserName", headerText: "User Name", width: "150", visible: true },
    {
      field: "UserTypeName",
      headerText: "User Type Name",
      width: "170",
      visible: true,
    },
    {
      field: "Description",
      headerText: "Description",
      width: "150",
      visible: true,
    },
    { field: "Mobile", headerText: "Mobile", width: "130", visible: true },
    { field: "Email", headerText: "Email", width: "160", visible: true },
    { field: "Status", headerText: "Status", width: "130", visible: true },
  ],
  Transaction: [
    {
      field: "CompanyName",
      headerText: "Company",
      width: "170",
      visible: true,
    },
    {
      field: "PartyLedgerName",
      headerText: "Party Name",
      width: "160",
      visible: true,
    },
    {
      field: "VoucherType",
      headerText: "Vch Type",
      width: "150",
      visible: true,
    },
    {
      field: "VoucherNumber",
      headerText: "Vch No.",
      width: "150",
      visible: true,
    },
    { field: "Date", headerText: "Date", width: "100", visible: true },

    {
      field: "Narration",
      headerText: "Narration",
      width: "160",
      visible: true,
    },
    {
      field: "IsCancelled",
      headerText: "Is Cancel",
      width: "160",
      visible: true,
    },
    {
      field: "IsDeleted",
      headerText: "Is Delete",
      width: "160",
      visible: true,
    },

    {
      field: "CreatedDate",
      headerText: "Uploaded On",
      width: "160",
      visible: true,
    },

    { field: "Status", headerText: "Status", width: "130", visible: true },
  ],
  ledger: [
    {
      field: "ParentName",
      headerText: "Parent",
      width: "160",
      visible: true,
    },
    {
      field: "CompanyName",
      headerText: "Company",
      width: "150",
      visible: true,
    },
    {
      field: "LedgerName",
      headerText: "Name",
      width: "150",
      visible: true,
    },

    {
      field: "ParentName",
      headerText: "Parent",
      width: "150",
      visible: true,
    },
    {
      field: "MailingName",
      headerText: "Mailing Name",
      width: "170",
      visible: true,
    },
    {
      field: "FullAddress",
      headerText: "Address",
      width: "170",
      visible: true,
    },
    {
      field: "CountryName",
      headerText: "Country",
      width: "170",
      visible: true,
    },
    {
      field: "StateName",
      headerText: "State",
      width: "170",
      visible: true,
    },
    { field: "Pincode", headerText: "Pincode", width: "170", visible: true },
    {
      field: "ContactPerson",
      headerText: "Contact Person",
      width: "170",
      visible: true,
    },
    { field: "MobileNo", headerText: "Mobile", width: "170", visible: true },
    { field: "PhoneNo", headerText: "Phone", width: "170", visible: true },
    { field: "EmailId", headerText: "Email Id", width: "170", visible: true },
    {
      field: "CCEmail",
      headerText: "CC Email Id",
      width: "170",
      visible: true,
    },
    { field: "PANNo", headerText: "PAN No.", width: "140", visible: true },
    {
      field: "GSTRegType",
      headerText: "Reg. Type",
      width: "170",
      visible: true,
    },
    { field: "GSTNo", headerText: "GST No.", width: "170", visible: true },
    {
      field: "OpeningBalance",
      headerText: "Opening Balance",
      width: "190",
      visible: true,
    },
    {
      field: "CreatedDate",
      headerText: "Uploaded ON",
      width: "170",
      visible: true,
    },

    { field: "Status", headerText: "Status", width: "130", visible: true },
  ],
  statistics: [
    { field: "Name", headerText: "Name", width: "150", visible: true },
    { field: "Active", headerText: "Active", width: "150", visible: true },
    { field: "Cancel", headerText: "Cancel", width: "150", visible: true },
    { field: "Total", headerText: "Total", width: "150", visible: true },
  ],
  statistics_1: [
    {
      field: "VoucherType",
      headerText: "Voucher Type",
      width: "160",
      visible: true,
    },
    { field: "Active", headerText: "Active", width: "150", visible: true },
    { field: "Cancel", headerText: "Cancel", width: "150", visible: true },
    { field: "Total", headerText: "Total", width: "150", visible: true },
  ],
  sync: [
    {
      field: "CompanyCode",
      headerText: "Company Code",
      width: "180",
      visible: true,
    },
    {
      field: "CompanyName",
      headerText: "Company Name",
      width: "180",
      visible: true,
    },
    {
      field: "LastTransactionSyncDate",
      headerText: "Last Transaction Sync Date",
      width: "200",
      visible: true,
    },
    {
      field: "TransactionSyncAging",
      headerText: "Transaction Sync Aging",
      width: "220",
      visible: true,
    },
    {
      field: "LastTransactionDate",
      headerText: "Last Transaction Date",
      width: "220",
      visible: true,
    },
    {
      field: "TransactionDateAging",
      headerText: "Transaction Date Aging",
      width: "220",
      visible: true,
    },
  ],
};
